import type { PlaceQuestion } from 'src/types';

export const QUESTIONS: PlaceQuestion[] = [
  {
    id: 'place-type',
    number: 1,
    question: 'What kind of place do you enjoy the most?',
    options: [
      'Art galleries',
      'Nature parks',
      'Historic buildings',
      'City streets and shops',
      'Stadiums',
      'Food markets',
      'Hip neighborhoods',
      'Sunset viewpoints',
      'Central squares',
      'Modern art museums',
    ],
  },
  {
    id: 'morning-activity',
    number: 2,
    question: 'What’s your ideal way to spend a morning?',
    options: [
      'Visiting exhibitions',
      'Walking under trees',
      'Exploring royal history',
      'Shopping and coffee',
      'Watching a football training',
      'Trying local tapas',
      'Taking street photos',
      'Relaxing in silence',
      'Sitting at a terrace',
      'Admiring creative works',
    ],
  },
  {
    id: 'personality',
    number: 3,
    question: 'Which word best describes you?',
    options: [
      'Artistic',
      'Calm',
      'Curious',
      'Social',
      'Passionate',
      'Foodie',
      'Trendy',
      'Dreamy',
      'Friendly',
      'Modern',
    ],
  },
  {
    id: 'time-of-day',
    number: 4,
    question: 'What’s your favorite time of day to explore?',
    options: [
      'Morning light',
      'Late morning',
      'Afternoon',
      'Evening buzz',
      'Match day',
      'Lunch hour',
      'Midnight streets',
      'Sunset',
      'Anytime',
      'Night inspiration',
    ],
  },
  {
    id: 'color-mood',
    number: 5,
    question: 'Pick a color that fits your mood in Madrid.',
    options: [
      'White',
      'Green',
      'Gold',
      'Neon',
      'Blue',
      'Red',
      'Pink',
      'Orange',
      'Yellow',
      'Black',
    ],
  },
  {
    id: 'travel-photo',
    number: 6,
    question: 'What’s your must-have travel photo?',
    options: [
      'Art close-up',
      'Fountain reflection',
      'Royal staircase',
      'City lights',
      'Stadium selfie',
      'Food table',
      'Street mural',
      'Sunset silhouette',
      'Crowd scene',
      'Abstract art',
    ],
  },
  {
    id: 'music',
    number: 7,
    question: 'What music do you prefer while exploring?',
    options: [
      'Classical',
      'Chill instrumental',
      'Cinematic soundtrack',
      'Pop',
      'Sports anthems',
      'Latin rhythms',
      'Indie rock',
      'Ambient',
      'Street musicians',
      'Experimental',
    ],
  },
  {
    id: 'travel-companion',
    number: 8,
    question: 'What’s your perfect travel companion?',
    options: [
      'Museum guide',
      'Park bench',
      'Audio tour',
      'Shopping friend',
      'Football buddy',
      'Chef or foodie',
      'Local artist',
      'Sunset watcher',
      'Street performer',
      'Photographer',
    ],
  },
  {
    id: 'souvenir',
    number: 9,
    question: 'What souvenir would you bring home?',
    options: [
      'Art print',
      'Leaf or flower',
      'Crown keychain',
      'T-shirt',
      'Ball or jersey',
      'Olive oil',
      'Vintage badge',
      'Postcard',
      'Magnet',
      'Sketchbook',
    ],
  },
  {
    id: 'travel-value',
    number: 10,
    question: 'What do you value most when traveling?',
    options: [
      'Culture',
      'Relaxation',
      'Heritage',
      'Energy',
      'Sports',
      'Taste',
      'Style',
      'Atmosphere',
      'People',
      'Creativity',
    ],
  },
  {
    id: 'activity-sounds-best',
    number: 11,
    question: 'Which activity sounds best?',
    options: [
      'Art tour',
      'Boat ride',
      'Royal visit',
      'Shopping walk',
      'Stadium tour',
      'Tapas tasting',
      'Vintage market',
      'Watching sunset',
      'Taking photos in the plaza',
      'Exploring a modern gallery',
    ],
  },
  {
    id: 'building-attracts-you',
    number: 12,
    question: 'What type of building attracts you?',
    options: [
      'Museum',
      'Greenhouse',
      'Palace',
      'Theatre',
      'Stadium',
      'Market',
      'Bar',
      'Temple',
      'Square',
      'Contemporary hall',
    ],
  },
  {
    id: 'favorite-sound',
    number: 13,
    question: 'Choose your favorite sound.',
    options: [
      'Quiet hall',
      'Birds singing',
      'Bells',
      'Street chatter',
      'Crowd cheering',
      'Frying food',
      'Music from bars',
      'Water flowing',
      'Laughter',
      'Silence before inspiration',
    ],
  },
  {
    id: 'inspiration',
    number: 14,
    question: 'What inspires you most?',
    options: [
      'Masterpieces',
      'Nature',
      'History',
      'City life',
      'Sportsmanship',
      'Flavors',
      'Youth culture',
      'Peaceful moments',
      'Meeting locals',
      'Modern ideas',
    ],
  },
  {
    id: 'smell-like',
    number: 15,
    question: 'Which smell do you like most?',
    options: [
      'Old books',
      'Fresh grass',
      'Polished marble',
      'Perfume',
      'Turf and sweat',
      'Paella',
      'Coffee',
      'Air after rain',
      'Street food',
      'Paint',
    ],
  },
  {
    id: 'outfit',
    number: 16,
    question: 'Which outfit fits your travel vibe?',
    options: [
      'Elegant',
      'Casual',
      'Classic',
      'Trendy',
      'Sporty',
      'Comfortable',
      'Urban',
      'Flowy',
      'Cheerful',
      'Artsy',
    ],
  },
  {
    id: 'rainy-day',
    number: 17,
    question: 'What would you do on a rainy day?',
    options: [
      'Visit a museum',
      'Sit in a greenhouse café',
      'Tour royal rooms',
      'Go shopping',
      'Watch football highlights',
      'Eat under the roof',
      'Listen to live music',
      'Watch the rain from a window',
      'People-watch indoors',
      'Sketch or paint',
    ],
  },
  {
    id: 'drink',
    number: 18,
    question: 'What do you drink while relaxing?',
    options: [
      'Wine',
      'Tea',
      'Coffee',
      'Cocktail',
      'Beer',
      'Fresh juice',
      'Mojito',
      'Smoothie',
      'Water',
      'Espresso',
    ],
  },
  {
    id: 'quote',
    number: 19,
    question: 'Which quote fits you?',
    options: [
      'Art is life.',
      'Breathe and let go.',
      'Every place tells a story.',
      'The city never sleeps.',
      'Never miss a match.',
      'Taste before you judge.',
      'Stay cool.',
      'The sun is my guide.',
      'Be in the moment.',
      'Create your path.',
    ],
  },
  {
    id: 'weekend',
    number: 20,
    question: 'Choose your perfect weekend.',
    options: [
      'Museum hopping',
      'Picnic',
      'Royal visit',
      'Shopping spree',
      'Game night',
      'Tapas crawl',
      'Party',
      'Sunset walk',
      'Plaza drinks',
      'Art fair',
    ],
  },
  {
    id: 'travel-speed',
    number: 21,
    question: 'What’s your travel speed?',
    options: [
      'Slow and thoughtful',
      'Easy and calm',
      'Curious and steady',
      'Fast and dynamic',
      'Adrenaline rush',
      'Taste and move',
      'Spontaneous',
      'Relaxed',
      'Casual',
      'Intense focus',
    ],
  },
  {
    id: 'emotion',
    number: 22,
    question: 'Which emotion do you chase while traveling?',
    options: [
      'Awe',
      'Peace',
      'Respect',
      'Joy',
      'Excitement',
      'Satisfaction',
      'Freedom',
      'Calm',
      'Connection',
      'Inspiration',
    ],
  },
  {
    id: 'view',
    number: 23,
    question: 'What’s your favorite view?',
    options: [
      'Framed paintings',
      'Lake reflections',
      'Castle roofs',
      'City skyline',
      'Stadium seats',
      'Colorful stands',
      'Murals',
      'Sunset horizon',
      'Square life',
      'Glass architecture',
    ],
  },
  {
    id: 'selfie-bg',
    number: 24,
    question: 'Pick your ideal background for a selfie.',
    options: [
      'Famous artwork',
      'Fountain',
      'Palace gate',
      'Bright lights',
      'Team flag',
      'Tapas plate',
      'Street art',
      'Sunset glow',
      'Archway',
      'Sculpture',
    ],
  },
  {
    id: 'season',
    number: 25,
    question: 'Which season would you visit Madrid?',
    options: [
      'Winter',
      'Spring',
      'Autumn',
      'Summer',
      'Summer nights',
      'Football season',
      'Any time food’s fresh',
      'Festival time',
      'Golden sunset season',
      'Holiday season',
      'Exhibition season',
    ],
  },
  {
    id: 'gift',
    number: 26,
    question: 'What gift would you give your guide?',
    options: [
      'Sketchbook',
      'Flower',
      'Book',
      'Coffee',
      'Scarf',
      'Tapas dish',
      'Vinyl record',
      'Candle',
      'Postcard',
      'Painting',
    ],
  },
  {
    id: 'perfect-trip',
    number: 27,
    question: 'What would make your trip perfect?',
    options: [
      'Art discovery',
      'Peaceful rest',
      'Historical insight',
      'Fun with friends',
      'Winning team',
      'New flavors',
      'Great music',
      'Magical sunset',
      'New connections',
      'Creative spark',
    ],
  },
  {
    id: 'last-day',
    number: 28,
    question: 'What would you do on your last day?',
    options: [
      'Visit final gallery',
      'Sit by the pond',
      'Take palace tour',
      'Walk down Gran Vía',
      'Catch a game',
      'Eat at market',
      'Go dancing',
      'Watch sunset',
      'Meet friends',
      'Visit museum gift shop',
    ],
  },
  {
    id: 'social-media-post',
    number: 29,
    question: 'What do you post on social media?',
    options: [
      'Museum photos',
      'Park vibes',
      'Royal elegance',
      'Street life',
      'Stadium shot',
      'Food highlights',
      'Vintage cafés',
      'Sunset reel',
      'Laughs with locals',
      'Art stories',
    ],
  },
  {
    id: 'farewell',
    number: 30,
    question: 'What do you say to Madrid before leaving?',
    options: [
      '“See you at the Prado.”',
      '“See you in Retiro.”',
      '“See you at the Palace.”',
      '“See you on Gran Vía.”',
      '“See you at Bernabéu.”',
      '“See you at the Market.”',
      '“See you in Malasaña.”',
      '“See you at Debod.”',
      '“See you in Plaza Mayor.”',
      '“See you at Reina Sofía.”',
    ],
  },
];
