import type { PlaceQuestion } from 'src/types';

export const QUESTIONS: PlaceQuestion[] = [
  {
    id: 'place-type',
    question: 'What kind of place do you enjoy the most?',
    options: [
      { number: 1, text: 'Art galleries' },
      { number: 2, text: 'Nature parks' },
      { number: 3, text: 'Historic buildings' },
      { number: 4, text: 'City streets and shops' },
      { number: 5, text: 'Stadiums' },
      { number: 6, text: 'Food markets' },
      { number: 7, text: 'Hip neighborhoods' },
      { number: 8, text: 'Sunset viewpoints' },
      { number: 9, text: 'Central squares' },
      { number: 10, text: 'Modern art museums' },
    ],
  },
  {
    id: 'morning-activity',
    question: 'What’s your ideal way to spend a morning?',
    options: [
      { number: 1, text: 'Visiting exhibitions' },
      { number: 2, text: 'Walking under trees' },
      { number: 3, text: 'Exploring royal history' },
      { number: 4, text: 'Shopping and coffee' },
      { number: 5, text: 'Watching a football training' },
      { number: 6, text: 'Trying local tapas' },
      { number: 7, text: 'Taking street photos' },
      { number: 8, text: 'Relaxing in silence' },
      { number: 9, text: 'Sitting at a terrace' },
      { number: 10, text: 'Admiring creative works' },
    ],
  },
  {
    id: 'personality',
    question: 'Which word best describes you?',
    options: [
      { number: 1, text: 'Artistic' },
      { number: 2, text: 'Calm' },
      { number: 3, text: 'Curious' },
      { number: 4, text: 'Social' },
      { number: 5, text: 'Passionate' },
      { number: 6, text: 'Foodie' },
      { number: 7, text: 'Trendy' },
      { number: 8, text: 'Dreamy' },
      { number: 9, text: 'Friendly' },
      { number: 10, text: 'Modern' },
    ],
  },
  {
    id: 'time-of-day',
    question: 'What’s your favorite time of day to explore?',
    options: [
      { number: 1, text: 'Morning light' },
      { number: 2, text: 'Late morning' },
      { number: 3, text: 'Afternoon' },
      { number: 4, text: 'Evening buzz' },
      { number: 5, text: 'Match day' },
      { number: 6, text: 'Lunch hour' },
      { number: 7, text: 'Midnight streets' },
      { number: 8, text: 'Sunset' },
      { number: 9, text: 'Anytime' },
      { number: 10, text: 'Night inspiration' },
    ],
  },
  {
    id: 'color-mood',
    question: 'Pick a color that fits your mood in Madrid.',
    options: [
      { number: 1, text: 'White' },
      { number: 2, text: 'Green' },
      { number: 3, text: 'Gold' },
      { number: 4, text: 'Neon' },
      { number: 5, text: 'Blue' },
      { number: 6, text: 'Red' },
      { number: 7, text: 'Pink' },
      { number: 8, text: 'Orange' },
      { number: 9, text: 'Yellow' },
      { number: 10, text: 'Black' },
    ],
  },
  {
    id: 'travel-photo',
    question: 'What’s your must-have travel photo?',
    options: [
      { number: 1, text: 'Art close-up' },
      { number: 2, text: 'Fountain reflection' },
      { number: 3, text: 'Royal staircase' },
      { number: 4, text: 'City lights' },
      { number: 5, text: 'Stadium selfie' },
      { number: 6, text: 'Food table' },
      { number: 7, text: 'Street mural' },
      { number: 8, text: 'Sunset silhouette' },
      { number: 9, text: 'Crowd scene' },
      { number: 10, text: 'Abstract art' },
    ],
  },
  {
    id: 'music',
    question: 'What music do you prefer while exploring?',
    options: [
      { number: 1, text: 'Classical' },
      { number: 2, text: 'Chill instrumental' },
      { number: 3, text: 'Cinematic soundtrack' },
      { number: 4, text: 'Pop' },
      { number: 5, text: 'Sports anthems' },
      { number: 6, text: 'Latin rhythms' },
      { number: 7, text: 'Indie rock' },
      { number: 8, text: 'Ambient' },
      { number: 9, text: 'Street musicians' },
      { number: 10, text: 'Experimental' },
    ],
  },
  {
    id: 'travel-companion',
    question: 'What’s your perfect travel companion?',
    options: [
      { number: 1, text: 'Museum guide' },
      { number: 2, text: 'Park bench' },
      { number: 3, text: 'Audio tour' },
      { number: 4, text: 'Shopping friend' },
      { number: 5, text: 'Football buddy' },
      { number: 6, text: 'Chef or foodie' },
      { number: 7, text: 'Local artist' },
      { number: 8, text: 'Sunset watcher' },
      { number: 9, text: 'Street performer' },
      { number: 10, text: 'Photographer' },
    ],
  },
  {
    id: 'souvenir',
    question: 'What souvenir would you bring home?',
    options: [
      { number: 1, text: 'Art print' },
      { number: 2, text: 'Leaf or flower' },
      { number: 3, text: 'Crown keychain' },
      { number: 4, text: 'T-shirt' },
      { number: 5, text: 'Ball or jersey' },
      { number: 6, text: 'Olive oil' },
      { number: 7, text: 'Vintage badge' },
      { number: 8, text: 'Postcard' },
      { number: 9, text: 'Magnet' },
      { number: 10, text: 'Sketchbook' },
    ],
  },
  {
    id: 'travel-value',
    question: 'What do you value most when traveling?',
    options: [
      { number: 1, text: 'Culture' },
      { number: 2, text: 'Relaxation' },
      { number: 3, text: 'Heritage' },
      { number: 4, text: 'Energy' },
      { number: 5, text: 'Sports' },
      { number: 6, text: 'Taste' },
      { number: 7, text: 'Style' },
      { number: 8, text: 'Atmosphere' },
      { number: 9, text: 'People' },
      { number: 10, text: 'Creativity' },
    ],
  },
  {
    id: 'activity-sounds-best',
    question: 'Which activity sounds best?',
    options: [
      { number: 1, text: 'Art tour' },
      { number: 2, text: 'Boat ride' },
      { number: 3, text: 'Royal visit' },
      { number: 4, text: 'Shopping walk' },
      { number: 5, text: 'Stadium tour' },
      { number: 6, text: 'Tapas tasting' },
      { number: 7, text: 'Vintage market' },
      { number: 8, text: 'Watching sunset' },
      { number: 9, text: 'Taking photos in the plaza' },
      { number: 10, text: 'Exploring a modern gallery' },
    ],
  },
  {
    id: 'building-attracts-you',
    question: 'What type of building attracts you?',
    options: [
      { number: 1, text: 'Museum' },
      { number: 2, text: 'Greenhouse' },
      { number: 3, text: 'Palace' },
      { number: 4, text: 'Theatre' },
      { number: 5, text: 'Stadium' },
      { number: 6, text: 'Market' },
      { number: 7, text: 'Bar' },
      { number: 8, text: 'Temple' },
      { number: 9, text: 'Square' },
      { number: 10, text: 'Contemporary hall' },
    ],
  },
  {
    id: 'favorite-sound',
    question: 'Choose your favorite sound.',
    options: [
      { number: 1, text: 'Quiet hall' },
      { number: 2, text: 'Birds singing' },
      { number: 3, text: 'Bells' },
      { number: 4, text: 'Street chatter' },
      { number: 5, text: 'Crowd cheering' },
      { number: 6, text: 'Frying food' },
      { number: 7, text: 'Music from bars' },
      { number: 8, text: 'Water flowing' },
      { number: 9, text: 'Laughter' },
      { number: 10, text: 'Silence before inspiration' },
    ],
  },
  {
    id: 'inspiration',
    question: 'What inspires you most?',
    options: [
      { number: 1, text: 'Masterpieces' },
      { number: 2, text: 'Nature' },
      { number: 3, text: 'History' },
      { number: 4, text: 'City life' },
      { number: 5, text: 'Sportsmanship' },
      { number: 6, text: 'Flavors' },
      { number: 7, text: 'Youth culture' },
      { number: 8, text: 'Peaceful moments' },
      { number: 9, text: 'Meeting locals' },
      { number: 10, text: 'Modern ideas' },
    ],
  },
  {
    id: 'smell-like',
    question: 'Which smell do you like most?',
    options: [
      { number: 1, text: 'Old books' },
      { number: 2, text: 'Fresh grass' },
      { number: 3, text: 'Polished marble' },
      { number: 4, text: 'Perfume' },
      { number: 5, text: 'Turf and sweat' },
      { number: 6, text: 'Paella' },
      { number: 7, text: 'Coffee' },
      { number: 8, text: 'Air after rain' },
      { number: 9, text: 'Street food' },
      { number: 10, text: 'Paint' },
    ],
  },
  {
    id: 'outfit',
    question: 'Which outfit fits your travel vibe?',
    options: [
      { number: 1, text: 'Elegant' },
      { number: 2, text: 'Casual' },
      { number: 3, text: 'Classic' },
      { number: 4, text: 'Trendy' },
      { number: 5, text: 'Sporty' },
      { number: 6, text: 'Comfortable' },
      { number: 7, text: 'Urban' },
      { number: 8, text: 'Flowy' },
      { number: 9, text: 'Cheerful' },
      { number: 10, text: 'Artsy' },
    ],
  },
  {
    id: 'rainy-day',
    question: 'What would you do on a rainy day?',
    options: [
      { number: 1, text: 'Visit a museum' },
      { number: 2, text: 'Sit in a greenhouse café' },
      { number: 3, text: 'Tour royal rooms' },
      { number: 4, text: 'Go shopping' },
      { number: 5, text: 'Watch football highlights' },
      { number: 6, text: 'Eat under the roof' },
      { number: 7, text: 'Listen to live music' },
      { number: 8, text: 'Watch the rain from a window' },
      { number: 9, text: 'People-watch indoors' },
      { number: 10, text: 'Sketch or paint' },
    ],
  },
  {
    id: 'drink',
    question: 'What do you drink while relaxing?',
    options: [
      { number: 1, text: 'Wine' },
      { number: 2, text: 'Tea' },
      { number: 3, text: 'Coffee' },
      { number: 4, text: 'Cocktail' },
      { number: 5, text: 'Beer' },
      { number: 6, text: 'Fresh juice' },
      { number: 7, text: 'Mojito' },
      { number: 8, text: 'Smoothie' },
      { number: 9, text: 'Water' },
      { number: 10, text: 'Espresso' },
    ],
  },
  {
    id: 'quote',
    question: 'Which quote fits you?',
    options: [
      { number: 1, text: 'Art is life.' },
      { number: 2, text: 'Breathe and let go.' },
      { number: 3, text: 'Every place tells a story.' },
      { number: 4, text: 'The city never sleeps.' },
      { number: 5, text: 'Never miss a match.' },
      { number: 6, text: 'Taste before you judge.' },
      { number: 7, text: 'Stay cool.' },
      { number: 8, text: 'The sun is my guide.' },
      { number: 9, text: 'Be in the moment.' },
      { number: 10, text: 'Create your path.' },
    ],
  },
  {
    id: 'weekend',
    question: 'Choose your perfect weekend.',
    options: [
      { number: 1, text: 'Museum hopping' },
      { number: 2, text: 'Picnic' },
      { number: 3, text: 'Royal visit' },
      { number: 4, text: 'Shopping spree' },
      { number: 5, text: 'Game night' },
      { number: 6, text: 'Tapas crawl' },
      { number: 7, text: 'Party' },
      { number: 8, text: 'Sunset walk' },
      { number: 9, text: 'Plaza drinks' },
      { number: 10, text: 'Art fair' },
    ],
  },
  {
    id: 'travel-speed',
    question: 'What’s your travel speed?',
    options: [
      { number: 1, text: 'Slow and thoughtful' },
      { number: 2, text: 'Easy and calm' },
      { number: 3, text: 'Curious and steady' },
      { number: 4, text: 'Fast and dynamic' },
      { number: 5, text: 'Adrenaline rush' },
      { number: 6, text: 'Taste and move' },
      { number: 7, text: 'Spontaneous' },
      { number: 8, text: 'Relaxed' },
      { number: 9, text: 'Casual' },
      { number: 10, text: 'Intense focus' },
    ],
  },
  {
    id: 'emotion',
    question: 'Which emotion do you chase while traveling?',
    options: [
      { number: 1, text: 'Awe' },
      { number: 2, text: 'Peace' },
      { number: 3, text: 'Respect' },
      { number: 4, text: 'Joy' },
      { number: 5, text: 'Excitement' },
      { number: 6, text: 'Satisfaction' },
      { number: 7, text: 'Freedom' },
      { number: 8, text: 'Calm' },
      { number: 9, text: 'Connection' },
      { number: 10, text: 'Inspiration' },
    ],
  },
  {
    id: 'view',
    question: 'What’s your favorite view?',
    options: [
      { number: 1, text: 'Framed paintings' },
      { number: 2, text: 'Lake reflections' },
      { number: 3, text: 'Castle roofs' },
      { number: 4, text: 'City skyline' },
      { number: 5, text: 'Stadium seats' },
      { number: 6, text: 'Colorful stands' },
      { number: 7, text: 'Murals' },
      { number: 8, text: 'Sunset horizon' },
      { number: 9, text: 'Square life' },
      { number: 10, text: 'Glass architecture' },
    ],
  },
  {
    id: 'selfie-bg',
    question: 'Pick your ideal background for a selfie.',
    options: [
      { number: 1, text: 'Famous artwork' },
      { number: 2, text: 'Fountain' },
      { number: 3, text: 'Palace gate' },
      { number: 4, text: 'Bright lights' },
      { number: 5, text: 'Team flag' },
      { number: 6, text: 'Tapas plate' },
      { number: 7, text: 'Street art' },
      { number: 8, text: 'Sunset glow' },
      { number: 9, text: 'Archway' },
      { number: 10, text: 'Sculpture' },
    ],
  },
  {
    id: 'season',
    question: 'Which season would you visit Madrid?',
    options: [
      { number: 1, text: 'Winter' },
      { number: 2, text: 'Spring' },
      { number: 3, text: 'Autumn' },
      { number: 4, text: 'Summer nights' },
      { number: 5, text: 'Football season' },
      { number: 6, text: 'Any time food’s fresh' },
      { number: 7, text: 'Festival time' },
      { number: 8, text: 'Golden sunset season' },
      { number: 9, text: 'Holiday season' },
      { number: 10, text: 'Exhibition season' },
    ],
  },
  {
    id: 'gift',
    question: 'What gift would you give your guide?',
    options: [
      { number: 1, text: 'Sketchbook' },
      { number: 2, text: 'Flower' },
      { number: 3, text: 'Book' },
      { number: 4, text: 'Coffee' },
      { number: 5, text: 'Scarf' },
      { number: 6, text: 'Tapas dish' },
      { number: 7, text: 'Vinyl record' },
      { number: 8, text: 'Candle' },
      { number: 9, text: 'Postcard' },
      { number: 10, text: 'Painting' },
    ],
  },
  {
    id: 'perfect-trip',
    question: 'What would make your trip perfect?',
    options: [
      { number: 1, text: 'Art discovery' },
      { number: 2, text: 'Peaceful rest' },
      { number: 3, text: 'Historical insight' },
      { number: 4, text: 'Fun with friends' },
      { number: 5, text: 'Winning team' },
      { number: 6, text: 'New flavors' },
      { number: 7, text: 'Great music' },
      { number: 8, text: 'Magical sunset' },
      { number: 9, text: 'New connections' },
      { number: 10, text: 'Creative spark' },
    ],
  },
  {
    id: 'last-day',
    question: 'What would you do on your last day?',
    options: [
      { number: 1, text: 'Visit final gallery' },
      { number: 2, text: 'Sit by the pond' },
      { number: 3, text: 'Take palace tour' },
      { number: 4, text: 'Walk down Gran Vía' },
      { number: 5, text: 'Catch a game' },
      { number: 6, text: 'Eat at market' },
      { number: 7, text: 'Go dancing' },
      { number: 8, text: 'Watch sunset' },
      { number: 9, text: 'Meet friends' },
      { number: 10, text: 'Visit museum gift shop' },
    ],
  },
  {
    id: 'social-media-post',
    question: 'What do you post on social media?',
    options: [
      { number: 1, text: 'Museum photos' },
      { number: 2, text: 'Park vibes' },
      { number: 3, text: 'Royal elegance' },
      { number: 4, text: 'Street life' },
      { number: 5, text: 'Stadium shot' },
      { number: 6, text: 'Food highlights' },
      { number: 7, text: 'Vintage cafés' },
      { number: 8, text: 'Sunset reel' },
      { number: 9, text: 'Laughs with locals' },
      { number: 10, text: 'Art stories' },
    ],
  },
  {
    id: 'farewell',
    question: 'What do you say to Madrid before leaving?',
    options: [
      { number: 1, text: '“See you at the Prado.”' },
      { number: 2, text: '“See you in Retiro.”' },
      { number: 3, text: '“See you at the Palace.”' },
      { number: 4, text: '“See you on Gran Vía.”' },
      { number: 5, text: '“See you at Bernabéu.”' },
      { number: 6, text: '“See you at the Market.”' },
      { number: 7, text: '“See you in Malasaña.”' },
      { number: 8, text: '“See you at Debod.”' },
      { number: 9, text: '“See you in Plaza Mayor.”' },
      { number: 10, text: '“See you at Reina Sofía.”' },
    ],
  },
];
